[tool.poetry]
name = "poetry_issue_celery"
version = "1.0.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.5"
celery = {version="*", source="douban"}

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.douban.com/simple/"
