[tool.poetry]
name = "poetry_issue_celery"
version = "0.1.0"
description = ""
authors = ["ocavue <ocavue@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = "3.1.23"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
